FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_MARKETING_OWNER_NAME
ARG VITE_MARKETING_OWNER_EMAIL
ARG VITE_MARKETING_OWNER_PHONE
ARG VITE_MARKETING_OWNER_WHATSAPP
ARG VITE_MARKETING_OWNER_COMPANY

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
ENV VITE_MARKETING_OWNER_NAME=${VITE_MARKETING_OWNER_NAME}
ENV VITE_MARKETING_OWNER_EMAIL=${VITE_MARKETING_OWNER_EMAIL}
ENV VITE_MARKETING_OWNER_PHONE=${VITE_MARKETING_OWNER_PHONE}
ENV VITE_MARKETING_OWNER_WHATSAPP=${VITE_MARKETING_OWNER_WHATSAPP}
ENV VITE_MARKETING_OWNER_COMPANY=${VITE_MARKETING_OWNER_COMPANY}

RUN test -n "${VITE_API_BASE_URL}" || (echo "Missing VITE_API_BASE_URL build arg" && exit 1)
RUN test -n "${VITE_SUPABASE_URL}" || (echo "Missing VITE_SUPABASE_URL build arg" && exit 1)
RUN test -n "${VITE_SUPABASE_ANON_KEY}" || (echo "Missing VITE_SUPABASE_ANON_KEY build arg" && exit 1)

RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1/ || exit 1
