import { Link as RouterLink } from "react-router-dom";

import pageStyles from "./Pages.module.css";

interface LegalSection {
    title: string;
    paragraphs?: string[];
    bullets?: string[];
}

function LegalDocumentPage({
    eyebrow,
    title,
    subtitle,
    sections
}: {
    eyebrow: string;
    title: string;
    subtitle: string;
    sections: LegalSection[];
}) {
    return (
        <div className={pageStyles.legalShell}>
            <article className={pageStyles.legalFrame}>
                <header className={pageStyles.legalHeader}>
                    <span className={pageStyles.legalEyebrow}>{eyebrow}</span>
                    <h1 className={pageStyles.legalTitle}>{title}</h1>
                    <p className={pageStyles.legalSubtitle}>{subtitle}</p>
                </header>

                <div className={pageStyles.legalActions}>
                    <RouterLink className="primary-button" to="/signin">
                        Back to Sign In
                    </RouterLink>
                    <RouterLink className="secondary-button" to="/">
                        Back to Home
                    </RouterLink>
                </div>

                {sections.map((section) => (
                    <section key={section.title} className={pageStyles.legalSection}>
                        <h3>{section.title}</h3>
                        {section.paragraphs?.map((paragraph) => (
                            <p key={paragraph}>{paragraph}</p>
                        ))}
                        {section.bullets?.length ? (
                            <ul>
                                {section.bullets.map((bullet) => (
                                    <li key={bullet}>{bullet}</li>
                                ))}
                            </ul>
                        ) : null}
                    </section>
                ))}
            </article>
        </div>
    );
}

const privacySections: LegalSection[] = [
    {
        title: "Information We Collect",
        bullets: [
            "User profile details needed for secure access and role assignment.",
            "Operational records generated through member, cash, loan, and reporting workflows.",
            "Technical metadata such as request identifiers and security logs for auditability."
        ]
    },
    {
        title: "How We Use Information",
        bullets: [
            "To provide secure platform access and role-based workspace controls.",
            "To process financial operations and maintain accounting and audit trails.",
            "To support compliance, fraud prevention, troubleshooting, and service reliability."
        ]
    },
    {
        title: "Data Security and Isolation",
        paragraphs: [
            "The platform applies tenant-scoped data isolation, role-based access controls, and server-side authorization checks.",
            "Sensitive operations are logged for governance, and financial events are recorded for traceability."
        ]
    },
    {
        title: "Data Retention and Disclosure",
        paragraphs: [
            "Operational and audit records are retained according to cooperative policy, legal obligations, and platform controls.",
            "Data is not disclosed to unauthorized parties and is processed only for legitimate operational and compliance purposes."
        ]
    }
];

const termsSections: LegalSection[] = [
    {
        title: "Use of the Platform",
        paragraphs: [
            "Access is granted only to authorized users created by approved tenant administrators or the platform owner.",
            "Users must operate within assigned roles and may not attempt unauthorized actions."
        ]
    },
    {
        title: "Account and Credential Responsibility",
        bullets: [
            "Users are responsible for protecting credentials and maintaining account security.",
            "Temporary credentials must be changed at first login where required.",
            "Unauthorized credential sharing is prohibited."
        ]
    },
    {
        title: "Operational and Financial Controls",
        paragraphs: [
            "The system enforces workflow, approval, and audit controls on sensitive operations.",
            "Users agree that records generated by authorized actions form part of the operational audit trail."
        ]
    },
    {
        title: "Compliance and Enforcement",
        paragraphs: [
            "Violation of role, security, or governance policies may result in access suspension or termination.",
            "Tenant operators remain responsible for complying with applicable cooperative, financial, and data regulations."
        ]
    }
];

export function PrivacyPolicyPage() {
    return (
        <LegalDocumentPage
            eyebrow="Legal"
            title="Privacy Policy"
            subtitle="This page outlines how data is handled in the SACCOS platform for secure operations, accountability, and compliance."
            sections={privacySections}
        />
    );
}

export function TermsAgreementPage() {
    return (
        <LegalDocumentPage
            eyebrow="Legal"
            title="Terms & Agreement"
            subtitle="These terms define acceptable use, account responsibilities, and governance expectations for all platform users."
            sections={termsSections}
        />
    );
}
