import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import type { StatementRow } from "../types/api";

interface MemberStatementPdfPayload {
    memberName: string;
    memberEmail?: string | null;
    tenantName?: string | null;
    branchName?: string | null;
    generatedBy?: string | null;
    totalSavings: number;
    shareCapital: number;
    outstandingLoan: number;
    netPosition: number;
    statements: StatementRow[];
}

function formatCurrency(value: number) {
    return new Intl.NumberFormat("en-TZ", {
        style: "currency",
        currency: "TZS",
        maximumFractionDigits: 0
    }).format(value || 0);
}

function formatDate(value?: string | null) {
    if (!value) {
        return "N/A";
    }

    return new Intl.DateTimeFormat("en-TZ", {
        dateStyle: "medium",
        timeStyle: "short"
    }).format(new Date(value));
}

function prettifyType(value: string) {
    return value
        .split("_")
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(" ");
}

export function downloadMemberStatementPdf(payload: MemberStatementPdfPayload) {
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "pt",
        format: "a4"
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 36;

    const colors = {
        primary: [10, 5, 115] as [number, number, number],
        accent: [31, 168, 230] as [number, number, number],
        text: [15, 23, 42] as [number, number, number],
        muted: [71, 85, 105] as [number, number, number],
        success: [22, 163, 74] as [number, number, number],
        danger: [220, 38, 38] as [number, number, number]
    };

    doc.setFillColor(...colors.primary);
    doc.rect(0, 0, pageWidth, 88, "F");
    doc.setFillColor(...colors.accent);
    doc.rect(0, 78, pageWidth, 10, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(17);
    doc.text("SMART SACCOS", margin, 34);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Member Financial Statement", margin, 52);

    const generatedAt = formatDate(new Date().toISOString());
    doc.text(`Generated: ${generatedAt}`, pageWidth - margin, 34, { align: "right" });
    doc.text(`Generated by: ${payload.generatedBy || "Member Portal"}`, pageWidth - margin, 52, { align: "right" });

    doc.setTextColor(...colors.text);
    let cursorY = 118;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Member Details", margin, cursorY);
    cursorY += 16;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...colors.muted);
    doc.text(`Name: ${payload.memberName}`, margin, cursorY);
    doc.text(`Email: ${payload.memberEmail || "N/A"}`, margin + 220, cursorY);
    cursorY += 14;
    doc.text(`SACCOS: ${payload.tenantName || "N/A"}`, margin, cursorY);
    doc.text(`Branch: ${payload.branchName || "N/A"}`, margin + 220, cursorY);
    cursorY += 20;

    const summaryCards = [
        { label: "Total Savings", value: formatCurrency(payload.totalSavings), tone: "success" as const },
        { label: "Share Capital", value: formatCurrency(payload.shareCapital), tone: "primary" as const },
        { label: "Outstanding Loan", value: formatCurrency(payload.outstandingLoan), tone: "danger" as const },
        { label: "Net Position", value: formatCurrency(payload.netPosition), tone: payload.netPosition < 0 ? "danger" : "success" as const }
    ];

    const cardGap = 10;
    const cardWidth = (pageWidth - margin * 2 - cardGap * 3) / 4;
    const cardHeight = 62;

    summaryCards.forEach((card, index) => {
        const x = margin + index * (cardWidth + cardGap);
        const y = cursorY;

        const bg = card.tone === "danger" ? [254, 242, 242] : card.tone === "success" ? [240, 253, 244] : [239, 246, 255];
        const border = card.tone === "danger" ? colors.danger : card.tone === "success" ? colors.success : colors.primary;

        doc.setFillColor(bg[0], bg[1], bg[2]);
        doc.roundedRect(x, y, cardWidth, cardHeight, 4, 4, "F");
        doc.setDrawColor(...border);
        doc.setLineWidth(0.7);
        doc.roundedRect(x, y, cardWidth, cardHeight, 4, 4, "S");

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...colors.muted);
        doc.text(card.label, x + 10, y + 18);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(...colors.text);
        doc.text(card.value, x + 10, y + 40);
    });

    cursorY += cardHeight + 24;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...colors.text);
    doc.text("Recent Transactions", margin, cursorY);
    cursorY += 10;

    const rows = payload.statements
        .slice(0, 250)
        .map((row) => ([
            formatDate(row.created_at || row.transaction_date),
            prettifyType(row.transaction_type),
            row.reference || "-",
            row.direction.toUpperCase(),
            formatCurrency(row.amount),
            formatCurrency(row.running_balance)
        ]));

    autoTable(doc, {
        startY: cursorY,
        head: [["Date", "Type", "Reference", "Direction", "Amount", "Balance After"]],
        body: rows.length ? rows : [["N/A", "No transactions available", "-", "-", "-", "-"]],
        theme: "grid",
        headStyles: {
            fillColor: colors.primary,
            textColor: 255,
            fontStyle: "bold",
            halign: "left"
        },
        styles: {
            font: "helvetica",
            fontSize: 8.5,
            cellPadding: 6,
            textColor: colors.text
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252]
        },
        columnStyles: {
            0: { cellWidth: 92 },
            1: { cellWidth: 100 },
            2: { cellWidth: 98 },
            3: { halign: "center", cellWidth: 62 },
            4: { halign: "right", cellWidth: 85 },
            5: { halign: "right", cellWidth: 95 }
        },
        margin: { left: margin, right: margin }
    });

    const pages = doc.getNumberOfPages();
    for (let page = 1; page <= pages; page += 1) {
        doc.setPage(page);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(...colors.muted);
        doc.text(
            `SMART SACCOS • Confidential Member Statement • Page ${page} of ${pages}`,
            pageWidth / 2,
            pageHeight - 18,
            { align: "center" }
        );
    }

    const stamp = new Date().toISOString().slice(0, 10);
    doc.save(`member-statement-${stamp}.pdf`);
}
